/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Parser.Parser;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.DocDir;
import model.Pat;
import model.PatDir;

/**
 *
 * @author kalindjoshi
 */
public class DocPanel extends javax.swing.JPanel {

    /**
     * Creates new form DocPanel
     */
    
    PatDir patDir;
    DocDir docDir;
    ArrayList<Pat> patList;
    DefaultTableModel model;
    DefaultTableModel model1;
    Pat pat;
    Pat pat1;
    Parser parser;
    boolean is_logged = false;
    
    public DocPanel() {
        initComponents();
    }

    public DocPanel(PatDir patDir, DocDir docDir){
        initComponents();
        
        this.patDir = patDir;
        patList = patDir.getPatList();
        this.docDir = docDir;
        
        model = (DefaultTableModel) person_dir_table.getModel();
        model.setRowCount(0);
        
        model1 = (DefaultTableModel) person_directory_table.getModel();
        model1.setRowCount(0);
                    
        for(Pat p:patList){
            Object[] row= new Object[3];
            row[0]= p.getId();
            row[1]= p.getPerson().getName();
            row[2]= p.getPerson().getAge();
            model.addRow(row);
            model1.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
