/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Parser.Parser;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doc;
import model.DocDir;
import model.Encounter;
import model.Pat;
import model.PatDir;
import model.VitalSigns;

/**
 *
 * @author kalindjoshi
 */
public class DocPanel extends javax.swing.JPanel {

    /**
     * Creates new form DocPanel
     */
    
    PatDir patDir;
    DocDir docDir;
    ArrayList<Pat> patList;
    ArrayList<Doc> DocList;
    DefaultTableModel model;
    DefaultTableModel model1;
    Pat pat;
    Pat pat1;
    Doc doc;
    Parser parser;
    boolean is_logged = false;
    Pat patAdd;
    Pat patView;
    Pat selectPat;
    boolean doclogin;
    
    
    
    
    
    
    public DocPanel() {
        initComponents();
    }

    public DocPanel(PatDir patDir, DocDir docDir){
        initComponents();
        
        this.patDir = patDir;
        DocList = docDir.getDocList();
        patList = patDir.getPatList();
        this.docDir = docDir;
        
        DocLogin.setVisible(true);
        
        model = (DefaultTableModel) PerDirTab.getModel();//personADirmodel
        model.setRowCount(0);
        
        
        model1 = (DefaultTableModel) PreEncTab.getModel();//personVdirmodel
        model1.setRowCount(0);
                    
        for(Pat p:patList){
            Object[] row= new Object[4];
            row[0]= p.getPid();
            row[1]= p.getPerson().getName();
            row[2]= p.getPerson().getAge();
            row[3]= p.getPerson().getCom();
            
            model.addRow(row);
            model1.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DocLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DocIdTxt = new javax.swing.JTextField();
        DocPassTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DocLogBtn = new javax.swing.JButton();
        DocEnc = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BPInput = new javax.swing.JTextField();
        HBInput = new javax.swing.JTextField();
        WeightInput = new javax.swing.JTextField();
        SympInput = new javax.swing.JTextField();
        addVital = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PerDirTab = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PreEncTab = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        encTab = new javax.swing.JTable();
        PrevEncBtn = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jLabel1.setText("Doc ID");

        DocPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocPassTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Password");

        DocLogBtn.setText("Login");
        DocLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocLogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DocLoginLayout = new javax.swing.GroupLayout(DocLogin);
        DocLogin.setLayout(DocLoginLayout);
        DocLoginLayout.setHorizontalGroup(
            DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocLoginLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DocLogBtn)
                    .addGroup(DocLoginLayout.createSequentialGroup()
                        .addGroup(DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DocPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(DocIdTxt))))
                .addGap(139, 139, 139))
        );
        DocLoginLayout.setVerticalGroup(
            DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocLoginLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DocIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(DocLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DocPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DocLogBtn)
                .addContainerGap(651, Short.MAX_VALUE))
        );

        add(DocLogin, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Blood Pressure", "Heartbeat", "Weight", "Symptoms"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Heartbeat");

        jLabel3.setText("Weight");

        jLabel4.setText("Symptoms");

        addVital.setText("Add ");
        addVital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalActionPerformed(evt);
            }
        });

        PerDirTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Community"
            }
        ));
        jScrollPane3.setViewportView(PerDirTab);

        jLabel5.setText("Blood Pressure");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addVital, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(BPInput)
                            .addComponent(HBInput)
                            .addComponent(WeightInput)
                            .addComponent(SympInput))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BPInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(HBInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(WeightInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SympInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(addVital)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("New Encounter", jPanel3);

        PreEncTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Community"
            }
        ));
        jScrollPane4.setViewportView(PreEncTab);

        encTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Enc ID", "Blood Pressure", "Heartbeat", "Weight", "Symptoms"
            }
        ));
        jScrollPane5.setViewportView(encTab);

        PrevEncBtn.setText("View Previous Reports");
        PrevEncBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrevEncBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(PrevEncBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(PrevEncBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("Previous Encounter", jPanel4);

        javax.swing.GroupLayout DocEncLayout = new javax.swing.GroupLayout(DocEnc);
        DocEnc.setLayout(DocEncLayout);
        DocEncLayout.setHorizontalGroup(
            DocEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        DocEncLayout.setVerticalGroup(
            DocEncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        add(DocEnc, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void PrevEncBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrevEncBtnActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) encTab.getModel();
        model.setRowCount(0);
        
        long patID = (long)model1.getValueAt(PreEncTab.getSelectedRow(), 0);
        patList = patDir.getPatList();
        for(Pat p: patList){
            if(patID == p.getPid())
            {
                selectPat = p;
            }
        }
        for(Encounter e: selectPat.getPatEncounterHistory()){
            Object [] row = new Object [6];
            row[0] = selectPat.getPerson().getName();
            row[1] = e.getEid();
            row[2] = e.getVitals().getBloodPressure();
            row[3] = e.getVitals().getHeartBeat();
            row[4] = e.getVitals().getBodyWeight();
            row[5] = e.getVitals().getSymptoms();
            model.addRow(row);
        }
        
        
    }//GEN-LAST:event_PrevEncBtnActionPerformed

    private void DocLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocLogBtnActionPerformed
        // TODO add your handling code here:
       long docID = Long.parseLong(DocIdTxt.getText());
       String docPass = String.valueOf(DocPassTxt.getText());
       
       for(Doc d: docDir.getDocList())
       {
           if(d.getDid() == docID && d.getDocPass() == null ? docPass == null : d.getDocPass().equals(docPass))
           {
           doclogin = true;
           }
               
       }
       if(doclogin)
       {
           DocLogin.setVisible(false);
           DocEnc.setVisible(true);
           
           DocList = docDir.getDocList();
           for(int i = 0; i< DocList.size(); i++)
           {
               if(docID == DocList.get(i).getDid())
               {
                  doc = DocList.get(i);
               }
           }
           populatePatTable();
       }
       else
       {
           JOptionPane.showMessageDialog(this, "Login to view encounters");
       }
       
    }//GEN-LAST:event_DocLogBtnActionPerformed

    private void DocPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocPassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocPassTxtActionPerformed

    private void addVitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalActionPerformed
        // TODO add your handling code here:
        if (PerDirTab.getSelectedRow()<0){
                JOptionPane.showMessageDialog(this, "Select a patient to add vitals");
        }
        else
        {
            long patIDChk= (long) model.getValueAt(PerDirTab.getSelectedRow(), 0);
            for(Pat p:patDir.getPatList()){
                if(patIDChk == p.getPid())
                {
                patAdd = p;
                }
            }
            float BP = Float.parseFloat(BPInput.getText());
            float HB = Float.parseFloat(HBInput.getText());
            float weight = Float.parseFloat(WeightInput.getText());
            String symp = SympInput.getText();
            
            patAdd.getEncounterHistory().addEncounter(new VitalSigns(BP, HB, weight, symp));
            JOptionPane.showMessageDialog(this, "Visit with Doctor saved");
        }
    }//GEN-LAST:event_addVitalActionPerformed

    public void populatePatTable()
       {
           model = (DefaultTableModel) PerDirTab.getModel();//personADirmodel
        model.setRowCount(0);
        
        model1 = (DefaultTableModel) PreEncTab.getModel();//personVdirmodel
        model1.setRowCount(0);
        
        for(Pat p:doc.getPD()){
            Object[] row= new Object[4];
            row[0]= p.getPid();
            row[1]= p.getPerson().getName();
            row[2]= p.getPerson().getAge();
            row[3]= p.getPerson().getCom();
            
            model.addRow(row);
            model1.addRow(row);
        }
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPInput;
    private javax.swing.JPanel DocEnc;
    private javax.swing.JTextField DocIdTxt;
    private javax.swing.JButton DocLogBtn;
    private javax.swing.JPanel DocLogin;
    private javax.swing.JTextField DocPassTxt;
    private javax.swing.JTextField HBInput;
    private javax.swing.JTable PerDirTab;
    private javax.swing.JTable PreEncTab;
    private javax.swing.JButton PrevEncBtn;
    private javax.swing.JTextField SympInput;
    private javax.swing.JTextField WeightInput;
    private javax.swing.JButton addVital;
    private javax.swing.JTable encTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
