/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Parser.Parser;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author kalindjoshi
 */
public class PatPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form PatPanel2
     */
    
    Com com = new Com();
    Pat pat =new Pat();
    ArrayList<Com> comList;
    ArrayList<Pat> patList;
    Parser parser = new Parser();
    PatDir patDir; 
    Hosp newHosp;
    ArrayList<Doc> docs;
    String patCom = "";
    City city;
    Com Comm;
    HospDir hospDir;
    Doc dd;
    Hosp hh;
    DefaultTableModel model;
    DocDir docDir;
    Pat patD;
    Doc docP;
    boolean patLogIn;
    Pat selectPat;
    
    ArrayList<Hosp> arr_hosp;
    
    
    public PatPanel2() {
        initComponents();
    }
     
    public PatPanel2(String[] communityList, PatDir patDir, Hosp newHospital, City city, HospDir hospDir, DocDir docDir){
        initComponents();  
        this.patDir = patDir;
        this.newHosp = newHospital;
        this.city = city;
        this.hospDir = hospDir;
        this.docDir = docDir;
        
        model = (DefaultTableModel) DocTable.getModel();
        model.setRowCount(0);
        
        PersonDrop.removeAllItems();
        
       
        for(Com commList:city.getComList()){
            PersonDrop.addItem(commList.getComName());
        }
        
        PersonDrop.removeAllItems();
        PersonDrop.addItem(" ");
        for(Com com: city.getComList())
        {
            PersonDrop.addItem(com.getComName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTable = new javax.swing.JScrollPane();
        DocTable = new javax.swing.JTable();
        DocView = new javax.swing.JButton();
        Appoint = new javax.swing.JButton();
        DrNameLbl = new javax.swing.JLabel();
        DrIdLbl = new javax.swing.JLabel();
        HosLbl = new javax.swing.JLabel();
        CommLbl = new javax.swing.JLabel();
        DrNameTxt = new javax.swing.JTextField();
        DrIdTxt = new javax.swing.JTextField();
        HosTxt = new javax.swing.JTextField();
        CommTxt = new javax.swing.JTextField();
        PersonDrop = new javax.swing.JComboBox<>();
        PersonLbl = new javax.swing.JTextField();
        PatIdLbl = new javax.swing.JTextField();
        PatIdTxt = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        LoginLandBtn = new javax.swing.JButton();
        patPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userIDInput = new javax.swing.JTextField();
        userPasswordInput = new javax.swing.JTextField();
        Searchbtn1 = new javax.swing.JButton();
        patPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        encountTab = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Available doctors for your area:");
        Heading.setViewportView(jTextArea2);

        DocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dr. Name", "Dr. ID", "Hospital ID", "Community"
            }
        ));
        jTable.setViewportView(DocTable);

        DocView.setText("View");
        DocView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocViewActionPerformed(evt);
            }
        });

        Appoint.setText("Book patient appointment");
        Appoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointActionPerformed(evt);
            }
        });

        DrNameLbl.setText("Dr. Name");

        DrIdLbl.setText("Dr. ID");

        HosLbl.setText("Hospital ID");

        CommLbl.setText("Community");

        HosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HosTxtActionPerformed(evt);
            }
        });

        PersonDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select community", "Allston", "Roslindale", " " }));

        PersonLbl.setText("Person Search");

        PatIdLbl.setText("Patient ID");

        PatIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatIdTxtActionPerformed(evt);
            }
        });

        Searchbtn.setText("Search");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        LoginLandBtn.setText("Login to see your reports");
        LoginLandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginLandBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patPanel1Layout = new javax.swing.GroupLayout(patPanel1);
        patPanel1.setLayout(patPanel1Layout);
        patPanel1Layout.setHorizontalGroup(
            patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patPanel1Layout.createSequentialGroup()
                        .addComponent(Searchbtn)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patPanel1Layout.createSequentialGroup()
                        .addComponent(LoginLandBtn)
                        .addContainerGap())))
            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(patPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTable)
                        .addGroup(patPanel1Layout.createSequentialGroup()
                            .addComponent(PersonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patPanel1Layout.createSequentialGroup()
                                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(126, 126, 126))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patPanel1Layout.createSequentialGroup()
                                        .addComponent(Appoint)
                                        .addGap(18, 18, 18)
                                        .addComponent(DocView)
                                        .addGap(31, 31, 31)))
                                .addGroup(patPanel1Layout.createSequentialGroup()
                                    .addComponent(PersonDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PatIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(PatIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(patPanel1Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CommLbl)
                                    .addGroup(patPanel1Layout.createSequentialGroup()
                                        .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DrNameLbl)
                                            .addComponent(DrIdLbl))
                                        .addGap(9, 9, 9)))
                                .addComponent(HosLbl))
                            .addGap(18, 18, 18)
                            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(DrNameTxt)
                                .addComponent(DrIdTxt)
                                .addComponent(HosTxt)
                                .addComponent(CommTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        patPanel1Layout.setVerticalGroup(
            patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(LoginLandBtn)
                .addGap(52, 52, 52)
                .addComponent(Searchbtn)
                .addContainerGap(418, Short.MAX_VALUE))
            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(patPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)
                    .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PersonLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PatIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PatIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PersonDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                    .addComponent(jTable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Appoint)
                        .addComponent(DocView))
                    .addGap(18, 18, 18)
                    .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DrNameLbl)
                        .addComponent(DrNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(patPanel1Layout.createSequentialGroup()
                            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(DrIdLbl)
                                .addComponent(DrIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(patPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(HosLbl)
                                .addComponent(HosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(CommLbl))
                        .addComponent(CommTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)))
        );

        add(patPanel1, "card3");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font(".AppleSystemUIFont", 3, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("View your records ");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("UserID");

        jLabel2.setText("Password");

        Searchbtn1.setText("Login");
        Searchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Searchbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patPanel2Layout = new javax.swing.GroupLayout(patPanel2);
        patPanel2.setLayout(patPanel2Layout);
        patPanel2Layout.setHorizontalGroup(
            patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Searchbtn1)
                    .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(patPanel2Layout.createSequentialGroup()
                            .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(51, 51, 51)
                            .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userPasswordInput)
                                .addComponent(userIDInput)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        patPanel2Layout.setVerticalGroup(
            patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(patPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Searchbtn1)
                .addGap(0, 328, Short.MAX_VALUE))
        );

        add(patPanel2, "card2");

        encountTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Blood Pressure", "Heartbeat", "Weight", "Symptoms"
            }
        ));
        jScrollPane5.setViewportView(encountTab);

        javax.swing.GroupLayout patPanel3Layout = new javax.swing.GroupLayout(patPanel3);
        patPanel3.setLayout(patPanel3Layout);
        patPanel3Layout.setHorizontalGroup(
            patPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        patPanel3Layout.setVerticalGroup(
            patPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        add(patPanel3, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void DocViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = DocTable.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Select a row and try again");
        }
        else{
            DefaultTableModel model = (DefaultTableModel) DocTable.getModel();
            long did = (long)model.getValueAt(DocTable.getSelectedRow(), 1);
            for(Hosp h: hospDir.getHospList()){
                for(Doc d:h.getDoctorHosp()){
                    if(d.getDid() == did){
                        hh = h;
                        dd = d;
                    }
                }
            }

            DrIdTxt.setText(String.valueOf(dd.getDid()));
            DrNameTxt.setText(String.valueOf((dd.getPerson().getName())));
            CommTxt.setText(String.valueOf(dd.getPerson().getCom()));
            HosTxt.setText(String.valueOf(hh.getHospNum()));
        }
    }//GEN-LAST:event_DocViewActionPerformed

    private void AppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointActionPerformed
        // TODO add your handling code here:
        if(DocTable.getSelectedRow()>=0 && !(PatIdTxt.getText().isEmpty()))
        {
            long choosedoc = (long) model.getValueAt(DocTable.getSelectedRow(), 1);
            long PatId = Long.parseLong(PatIdTxt.getText());
            for(Pat pat: patDir.getPatList()){
                if(PatId == pat.getPid()){
                    patD = pat;
                }
            }
            for(Doc doc: docDir.getDocList()){
                if(choosedoc == doc.getDid()){
                    docP = doc;
                    if(!(doc.getPD().contains(docP))){
                        doc.AppointPat(patD);
                        JOptionPane.showMessageDialog(this, "Booked Appointment with Dr.");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Select a doctor to book appointment");
                    }
                }
            }

        }
        else{
            JOptionPane.showMessageDialog(this, "You need to be a patient to book appointment");
        }

    }//GEN-LAST:event_AppointActionPerformed

    private void HosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HosTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HosTxtActionPerformed

    private void PatIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatIdTxtActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
        System.out.println(PatIdTxt.getText());
        System.out.println(PersonDrop.getSelectedItem().toString());

        if(PatIdTxt.getText().isEmpty() && PersonDrop.getSelectedItem().toString() == " "){
            JOptionPane.showMessageDialog(this, "Cannot keep both options empty");
        }
        else if(!PatIdTxt.getText().isEmpty() && PersonDrop.getSelectedItem().toString() != " "){
            System.out.println("patient_id.getText(): "+PatIdTxt.getText());
            System.out.println("doctor_community_dropbox.getSelectedItem().toString(): "+PersonDrop.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Please Use only one option");
        }
        else{
            if(!PatIdTxt.getText().isEmpty()){
                patList = patDir.getPatList();
                for(int i=0; i<patList.size();i++){
                    System.out.println("Inside Pat Dir traversal");
                    System.out.println(patList.get(i).getPerson().getName());
                    if(Integer.parseInt(PatIdTxt.getText()) == patList.get(i).getPid() ){
                        Person p = patList.get(i).getPerson();
                        patCom = p.getCom();
                        System.out.println("Patient belongs to:"+patCom);
                    }
                }
                if(patCom == ""){
                    JOptionPane.showMessageDialog(this, "Patient not found");
                }
                else{

                    Com a;

                    ArrayList<Doc> doc_hosp_comm;

                    ArrayList<Com> arr_comm =city.getComList();
                    for(Com i : arr_comm){
                        if(i.getComName() == patCom){
                            arr_hosp= i.getHospitalList();
                        }
                    }

                    for(Hosp j:arr_hosp){
                        doc_hosp_comm = j.getDoctorHosp();

                        DefaultTableModel model = (DefaultTableModel) DocTable.getModel();
                        model.setRowCount(0);

                        for(Doc i: doc_hosp_comm){
                            Object[] row = new Object[4];
                            row[0] = i.getPerson().getName();
                            row[1] = i.getDid();
                            row[2] = patCom;
                            row[3] = j.getHospNum();
                            model.addRow(row);
                        }
                    }

                }

            }//end if search by pid

            if(PersonDrop.getSelectedItem().toString() != " "){

                String searchDoctorComm = PersonDrop.getSelectedItem().toString();
                for(Com c: city.getComList()){
                    if(c.getComName() == searchDoctorComm)
                    com = c;
                }

                DefaultTableModel model = (DefaultTableModel) DocTable.getModel();
                model.setRowCount(0);

                for(Hosp h: com.getHospitalList()){
                    for(Doc d : h.getDoctorHosp()){
                        Object[] row = new Object[4];
                        row[0] = d.getPerson().getName();
                        row[1] = d.getDid();
                        row[2] = searchDoctorComm;
                        row[3] = h.getHospNum();
                        model.addRow(row);
                    }
                }
            }

        }
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void LoginLandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginLandBtnActionPerformed
        // TODO add your handling code here:
//        PatPanel2 patpanel2 = new PatPanel2();
        patPanel2.setVisible(true);
        patPanel1.setVisible(false);

    }//GEN-LAST:event_LoginLandBtnActionPerformed

    private void Searchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Searchbtn1ActionPerformed
        // TODO add your handling code here:
        patPanel3.setVisible(true);
        patPanel2.setVisible(false);
        DefaultTableModel encTabMod = (DefaultTableModel) encountTab.getModel();
        encTabMod.setRowCount(0);
        
        long userIDCred = Long.parseLong(userIDInput.getText());
        String userPassCred = String.valueOf(userPasswordInput.getText());
        
        for(Pat p: patDir.getPatList()){
            if(p.getPid() == userIDCred && (p.getUserPass() == null ? userPassCred == null : p.getUserPass().equals(userPassCred))){
                patLogIn = true;
            }
        }
        if(patLogIn){
            patList = patDir.getPatList();
            for(int i = 0; i < patList.size(); i++){
                if(userIDCred == patList.get(i).getPid()){
                    Person p = patList.get(i).getPerson();
                    patCom = p.getCom();
                }
            }
            for(Pat p: patList){
                if(userIDCred == p.getPid()){
                    selectPat = p;
                }
            }
            for(Encounter e: selectPat.getPatEncounterHistory()){
                Object[] row = new Object[4];
                row[0] = e.getEid();
                row[1] = e.getLastVisitDate();
                row[2] = e.getVitals().getBloodPressure();
                row[3] = e.getVitals().getHeartBeat();
                encTabMod.addRow(row);
            }
            
        }
        else{
        JOptionPane.showMessageDialog(this, "Please login to view reports");
        
        }
    }//GEN-LAST:event_Searchbtn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Appoint;
    private javax.swing.JLabel CommLbl;
    private javax.swing.JTextField CommTxt;
    private javax.swing.JTable DocTable;
    private javax.swing.JButton DocView;
    private javax.swing.JLabel DrIdLbl;
    private javax.swing.JTextField DrIdTxt;
    private javax.swing.JLabel DrNameLbl;
    private javax.swing.JTextField DrNameTxt;
    private javax.swing.JScrollPane Heading;
    private javax.swing.JLabel HosLbl;
    private javax.swing.JTextField HosTxt;
    private javax.swing.JButton LoginLandBtn;
    private javax.swing.JTextField PatIdLbl;
    private javax.swing.JTextField PatIdTxt;
    private javax.swing.JComboBox<String> PersonDrop;
    private javax.swing.JTextField PersonLbl;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JButton Searchbtn1;
    private javax.swing.JTable encountTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel patPanel1;
    private javax.swing.JPanel patPanel2;
    private javax.swing.JPanel patPanel3;
    private javax.swing.JTextField userIDInput;
    private javax.swing.JTextField userPasswordInput;
    // End of variables declaration//GEN-END:variables
}
