/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Com;
import model.DocDir;
import model.Encounter;
import model.EncounterHis;
import model.HeadClass;
import model.Hosp;
import model.HospDir;
import model.House;
import model.Pat;
import model.PatDir;
import model.Person;
import model.PersonDir;
import model.VitalSigns;

/**
 *
 * @author kalindjoshi
 */
public class SysAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminPanel
     */
    
    City city;
    String[] comList;
    String[] comDropboxList;
    PatDir patDir;
    Hosp newHosp;
    HospDir hospDir;
    EncounterHis encounterDir;
    PersonDir pd;
    DocDir docDir;
    HeadClass sys;
    Pat pat;
    Pat pat1;
    DefaultTableModel model_dr;
    DefaultTableModel model_dr1;
    ArrayList<Pat> patList;
    Pat selectedPat;
    VitalSigns selectedPatVitalSigns;
    Encounter enc;
    DefaultTableModel model_hosp;
    DefaultTableModel model;
    String selectedCom;
    Com com;
    Hosp hosp;
    HospDir hospDirectory;
    Person selectedPerson;
    Hosp selectedHosp;
    
    public SysAdminPanel()
    {
        initComponents();
    }
    
    public SysAdminPanel(City city, String[] communityDropboxList, PatDir patDir, HospDir hospDir,PersonDir pd, DocDir docDir, HeadClass sys){
        initComponents();
        this.city = city;
        this.communityDropboxList = communityDropboxList;
        this.pd=pd;
        this.docDir=docDir;
        this.sys = sys;
        this.patDir = patDir;
        this.hospDir = hospDir;
       
        patList = patDir.getPatList();
        this.docDir = docDir;
        
        showPersonTable();
        showCityTable();
        showCommunityTable();
        showPatientTable();
        
        
        for(Com commList:city.getComList()){
            for(House hosList: commList.getHouseList()){
                houselistComboBox.addItem(String.valueOf(hosList.getHouseNum()));
            }
        }
        
        community_dropbox.removeAllItems();
        for(Com c: city.getComList()){
            community_dropbox.addItem(c.getComName());
        }
        
//        for(House h: community.getHouseList()){
        model_dr = (DefaultTableModel) person_dir_table.getModel();
        model_dr.setRowCount(0);
        
        model_dr1 = (DefaultTableModel) person_directory_table.getModel();
        model_dr1.setRowCount(0);
        
        model = (DefaultTableModel) hospital_table.getModel();
        
        for(Pat p:patList){
            Object[] row= new Object[3];
            row[0]= p.getId();
            row[1]= p.getPerson().getName();
            row[2]= p.getPerson().getAge();
            model_dr.addRow(row);
            model_dr1.addRow(row);
        }
        
        patient_dropbox.removeAllItems();
        for(Pat p: patDir.getPatList()){
            patient_dropbox.addItem(String.valueOf(p.getId()));
        }
        
        
        ArrayList<Integer> aa = new ArrayList<Integer>();
            
    for(Com c: city.getComList()){
        for(Hosp h: c.getHospitalList()){
            aa.add(h.getHospNum());
        }      
    }
            
    hopital_list.removeAllItems();
      
    for(int s:aa){
       hopital_list.addItem(String.valueOf(s));
        }
    
    }

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton8.setText("Manage Community");

        jButton9.setText("Manage Doctor");

        jButton10.setText("Manage Hospital");

        jButton13.setText("Manage Patient");

        jButton6.setText("Manage Person");

        jButton7.setText("Manage Encounter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
